# Generated by Django 4.0.1 on 2022-01-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('cod_service', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
    ]
