# Generated by Django 4.0.1 on 2022-01-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_room_cost_per_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guests', models.PositiveSmallIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.TextField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagado'), ('ELI', 'Eliminado')], max_length=3)),
                ('payment_method', models.TextField(choices=[('EFEC', 'Pago en Efectivo'), ('TAR', 'Pago con Tarjeta de Crédito o Débito'), ('PAYP', 'Pago por Paypal')], max_length=4)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='Invoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.TextField(max_length=50)),
                ('nit', models.TextField(max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
            ],
        ),
    ]
