## registrar factura
POST http://127.0.0.1:8000/api/invoice/
content-type: application/json

{
    "amount":154.10,
    "name":"Juan Perez",
    "nit":"1545454",
    "booking_id":1
}

### obtener factura
GET http://127.0.0.1:8000/api/invoice/5/
Authorization: Beaer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQxNjY0NDI2LCJpYXQiOjE2NDE2NjQxMjYsImp0aSI6ImIzNjFjZjk4MTgyZDQzMWViZjRmYTE4YzVmYTUxYzNmIiwidXNlcl9pZCI6MX0.X2bZfcWhhQZO9ehu-n-fdKvzDP7aX9MZ8zCmhdqUYpk
content-type: application/json